name: Build

on:
  workflow_call:

env:
  DOTNET_VERSION: '8.0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Nuget Cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore
