name: Build

on:
  workflow_call:

env:
  DOTNET_VERSION: '8.0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Setup .NET
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Nuget Cache
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore
