name: Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_NAME: PinguApps.AppwriteMigrator
  DOTNET_VERSION: '8.0'

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/_build.yml
    secrets: inherit
